<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreEmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;
use App\Models\BankType;
use App\Models\Company;
use App\Models\DocumentType;
use App\Models\Employee;
use App\Models\Folder;
use App\Models\FolderLocation;
use App\Services\AuditService;
use Illuminate\Support\Facades\DB;

class EmployeeController extends Controller
{
    /**
     * Show the blank 201 File form (new employee).
     */
    public function create()
    {
        $companies = Company::where('is_active', true)->orderBy('name')->get();
        $bankTypes = BankType::where('is_active', true)->orderBy('name')->get();
        $folders   = \App\Models\Folder::where('is_available', true)->get();
        $locations = FolderLocation::withCount('employees')->orderByRaw('LENGTH(row_name) ASC')->orderBy('row_name', 'ASC')->get();
        $lastFolderCode = \App\Models\Folder::where('folder_code', 'like', 'CSC-HR-%')->max('folder_code');

        return view('201files', [
            'employee'       => null,
            'companies'      => $companies,
            'bankTypes'      => $bankTypes,
            'folders'        => $folders,
            'locations'      => $locations,
            'lastFolderCode' => $lastFolderCode,
        ]);
    }

    /**
     * Store a newly created employee.
     */
    public function store(StoreEmployeeRequest $request)
    {
        $employee = DB::transaction(function () use ($request) {
            $data = $request->only([
                'system_id', 'first_name', 'middle_name', 'last_name',
                'suffix', 'date_hired', 'status', 'barcode_id',
                'company_id', 'folder_id', 'folder_location_id', 'atm_status', 'bank_type_id',
            ]);

            $employee = Employee::create($data);

            // Auto-assign or Use Provided Folder Code
            $fullCode = $request->folder_code; // Already prepared with prefix in StoreEmployeeRequest if numeric
            
            if (empty($fullCode)) {
                // Auto-assignment logic (first available reuse, then next sequential)
                $folder = \App\Models\Folder::where('is_available', true)->orderBy('id')->first();

                if (!$folder) {
                    $lastFolderCode = \App\Models\Folder::where('folder_code', 'like', 'CSC-HR-%')->max('folder_code');
                    $numericPart = $lastFolderCode ? preg_replace('/[^0-9]/', '', $lastFolderCode) : '0000';
                    $nextNumber = intval($numericPart) + 1;
                    $dynamicMaxLength = max(4, strlen($numericPart));
                    $autoGeneratedCode = 'CSC-HR-' . str_pad($nextNumber, $dynamicMaxLength, '0', STR_PAD_LEFT);

                    $folder = \App\Models\Folder::create([
                        'folder_code' => $autoGeneratedCode,
                        'is_available' => false,
                    ]);
                } else {
                    $folder->update(['is_available' => false]);
                }
            } else {
                // Use the code provided (prefixed by Request if only numeric was sent)
                $folder = \App\Models\Folder::updateOrCreate(
                    ['folder_code' => $fullCode],
                    ['is_available' => false]
                );
            }

            $employee->folder_id = $folder->id;
            $employee->saveQuietly();

            // Create Hiring Event persistence record
            if ($employee->date_hired) {
                \App\Models\HiringEvent::updateOrCreate(
                    ['employee_id' => $employee->id],
                    ['event_date' => $employee->date_hired]
                );
            }

            $fresh = $employee->fresh()->load(['company', 'folder', 'folderLocation', 'bankType']);
            $after = $fresh->only([
                'system_id', 'first_name', 'middle_name', 'last_name',
                'suffix', 'date_hired', 'status', 'barcode_id',
                'company_id', 'folder_id', 'folder_location_id', 'atm_status', 'bank_type_id',
            ]);

            // Resolve descriptive names for logging
            $after['bank_name']     = $fresh->bankType?->name ?? 'N/A';
            $after['company_name']  = $fresh->company?->name ?? 'N/A';
            $after['folder_code']   = $fresh->folder?->folder_code ?? 'N/A';
            $after['location_name'] = $fresh->folderLocation?->full_location ?? 'N/A';

            unset($after['bank_type_id'], $after['company_id'], $after['folder_id'], $after['folder_location_id']);

            AuditService::log(
                'created',
                "Added new employee: " . $employee->full_name,
                $employee,
                ['before' => [], 'after' => $after]
            );

            // If created as resigned, auto-archive
            if ($employee->status === 'resigned') {
                $employee->update(['archive_date' => now()]);
                $employee->delete(); // soft-delete = archive
                AuditService::log(
                    'archived',
                    "Auto-archived employee (status: resigned)",
                    $employee
                );
            }

            return $employee;
        });

        if ($employee->trashed()) {
            return redirect()
                ->route('archives.index', ['tab' => 'employees'])
                ->with('success', 'Employee created and automatically archived (resigned).');
        }

        return redirect()
            ->route('employees.show', $employee)
            ->with('success', 'Employee profile created successfully.');
    }

    /**
     * Show an employee's 201 profile hub.
     */
    public function show(Employee $employee)
    {
        $employee->load(['company', 'folder', 'folderLocation', 'bankType']);

        $latestUpdate = \App\Models\AuditLog::where('model_type', Employee::class)
            ->where('model_id', $employee->id)
            ->whereIn('action', ['created', 'updated', 'restored'])
            ->with('user')
            ->latest()
            ->first();

        $companies = Company::where('is_active', true)->orderBy('name')->get();
        $bankTypes = BankType::where('is_active', true)->orderBy('name')->get();
        $folders   = \App\Models\Folder::where('is_available', true)->get();
        $locations = FolderLocation::withCount('employees')->orderByRaw('LENGTH(row_name) ASC')->orderBy('row_name', 'ASC')->get();
        $lastFolderCode = \App\Models\Folder::where('folder_code', 'like', 'CSC-HR-%')->max('folder_code');

        return view('201files', [
            'employee'       => $employee,
            'latestUpdate'   => $latestUpdate,
            'companies'      => $companies,
            'bankTypes'      => $bankTypes,
            'folders'        => $folders,
            'locations'      => $locations,
            'lastFolderCode' => $lastFolderCode,
        ]);
    }

    /**
     * Update an existing employee.
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee)
    {
        DB::transaction(function () use ($request, $employee) {
            $oldStatus = $employee->status;
            $oldFolderId = $employee->folder_id;

            $old = $employee->only([
                'system_id', 'first_name', 'middle_name', 'last_name',
                'suffix', 'date_hired', 'status', 'barcode_id',
                'company_id', 'folder_id', 'folder_location_id', 'atm_status', 'bank_type_id',
            ]);

            // Resolve descriptive names for logging (Old state)
            $old['bank_name']     = $employee->bankType?->name ?? 'N/A';
            $old['company_name']  = $employee->company?->name ?? 'N/A';
            $old['folder_code']   = $employee->folder?->folder_code ?? 'N/A';
            $old['location_name'] = $employee->folderLocation?->full_location ?? 'N/A';

            unset($old['bank_type_id'], $old['company_id'], $old['folder_id'], $old['folder_location_id']);

            $employee->update($request->only([
                'system_id', 'first_name', 'middle_name', 'last_name',
                'suffix', 'date_hired', 'status', 'barcode_id',
                'company_id', 'folder_id', 'folder_location_id', 'atm_status', 'bank_type_id',
            ]));

            // Sync Hiring Event if date_hired is present
            if ($employee->date_hired) {
                \App\Models\HiringEvent::updateOrCreate(
                    ['employee_id' => $employee->id],
                    ['event_date' => $employee->date_hired]
                );
            }

            $fresh = $employee->fresh()->load(['company', 'folder', 'folderLocation', 'bankType']);
            $after = $fresh->only([
                'system_id', 'first_name', 'middle_name', 'last_name',
                'suffix', 'date_hired', 'status', 'barcode_id',
                'company_id', 'folder_id', 'folder_location_id', 'atm_status', 'bank_type_id',
            ]);

            // Resolve descriptive names for logging (New state)
            $after['bank_name']     = $fresh->bankType?->name ?? 'N/A';
            $after['company_name']  = $fresh->company?->name ?? 'N/A';
            $after['folder_code']   = $fresh->folder?->folder_code ?? 'N/A';
            $after['location_name'] = $fresh->folderLocation?->full_location ?? 'N/A';

            unset($after['bank_type_id'], $after['company_id'], $after['folder_id'], $after['folder_location_id']);

            // Auto-assign or Use Provided Folder Code
            if ($request->has('folder_code')) {
                $fullCode = $request->folder_code; // Already prepared with prefix in UpdateEmployeeRequest if numeric

                if (empty($fullCode)) {
                    // Only auto-assign if they don't already have one
                    if (!$employee->folder_id) {
                        $folder = \App\Models\Folder::where('is_available', true)->orderBy('id')->first();

                        if (!$folder) {
                            $lastFolderCode = \App\Models\Folder::where('folder_code', 'like', 'CSC-HR-%')->max('folder_code');
                            $numericPart = $lastFolderCode ? preg_replace('/[^0-9]/', '', $lastFolderCode) : '0000';
                            $nextNumber = intval($numericPart) + 1;
                            $dynamicMaxLength = max(4, strlen($numericPart));
                            $autoGeneratedCode = 'CSC-HR-' . str_pad($nextNumber, $dynamicMaxLength, '0', STR_PAD_LEFT);

                            $folder = \App\Models\Folder::create([
                                'folder_code' => $autoGeneratedCode,
                                'is_available' => false,
                            ]);
                        } else {
                            $folder->update(['is_available' => false]);
                        }
                        $employee->folder_id = $folder->id;
                        $employee->saveQuietly();
                    }
                } else {
                    $folder = \App\Models\Folder::where('folder_code', $fullCode)->first();

                    if ($folder) {
                        // If it's a different folder than currently assigned, free the old one
                        if ($oldFolderId && $oldFolderId !== $folder->id) {
                            \App\Models\Folder::where('id', $oldFolderId)->update(['is_available' => true]);
                        }
                        
                        $folder->update(['is_available' => false]);
                        $employee->folder_id = $folder->id;
                        $employee->saveQuietly();
                    } else {
                        // Code doesn't exist. 
                        if ($employee->folder_id) {
                            // If employee has a folder, just update its code
                            \App\Models\Folder::where('id', $employee->folder_id)->update([
                                'folder_code' => $fullCode,
                                'is_available' => false,
                            ]);
                        } else {
                            // Create new folder
                            $folder = \App\Models\Folder::create([
                                'folder_code' => $fullCode,
                                'is_available' => false,
                            ]);
                            $employee->folder_id = $folder->id;
                            $employee->saveQuietly();
                        }
                    }
                }
            }

            AuditService::log(
                'updated',
                "Updated employee profile",
                $employee,
                ['before' => $old, 'after' => $after]
            );

            // Auto-archive if status changed to resigned
            if ($oldStatus !== 'resigned' && $employee->status === 'resigned') {
                $employee->update(['archive_date' => now()]);
                
                $employee->delete(); // soft-delete = archive
                AuditService::log(
                    'archived',
                    "Archived employee (status: resigned)",
                    $employee
                );
            }
        });

        if ($employee->trashed()) {
            return redirect()
                ->route('archives.index', ['tab' => 'employees'])
                ->with('success', 'Employee has been resigned and moved to the archive.');
        }

        return redirect()
            ->route('employees.show', $employee)
            ->with('success', 'Employee profile updated successfully.');
    }

    /**
     * List archived (soft-deleted resigned) employees. Admin only.
     */
    public function archiveIndex()
    {
        $employees = Employee::archived()
            ->with(['folder', 'folderLocation'])
            ->orderBy('deleted_at', 'desc')
            ->get();

        return view('employees.archive', compact('employees'));
    }

    /**
     * Restore an archived employee. Admin only.
     */
    public function restore(int $id)
    {
        $employee = Employee::withTrashed()->findOrFail($id);

        DB::transaction(function () use ($employee) {
            if ($employee->trashed()) {
                $employee->restore();
            }
            $employee->update([
                'status' => 'active',
                'archive_date' => null,
            ]);

            // Folder remains occupied (is_available stays false) during archive/restore cycle.

            AuditService::log(
                'restored',
                "Restored employee from archive",
                $employee
            );
        });

        return redirect()
            ->route('employees.show', $employee)
            ->with('success', 'Employee restored successfully.');
    }

    /**
     * Permanently delete an archived employee. Admin only.
     * This frees the slot (is_available = true).
     */
    public function forceDestroy(int $id)
    {
        if (!auth()->user()->isAdmin()) {
            abort(403, 'Unauthorized action.');
        }

        $employee = Employee::onlyTrashed()->findOrFail($id);

        DB::transaction(function () use ($employee) {
            // Free the folder if assigned
            if ($employee->folder_id) {
                \App\Models\Folder::where('id', $employee->folder_id)->update(['is_available' => true]);
            }

            $name = $employee->full_name;
            $systemId = $employee->system_id;

            AuditService::log(
                'deleted',
                "Permanently deleted employee (System ID: {$systemId})",
                $employee
            );

            $employee->forceDelete();
        });

        return redirect()
            ->route('archives.index', ['tab' => 'employees'])
            ->with('success', 'Employee permanently deleted. Folder is now available.');
    }
    /**
     * Get employee details as JSON (for Archive modal).
     */
    public function details(int $id)
    {
        $employee = Employee::withTrashed()
            ->with(['company', 'folder', 'folderLocation'])
            ->findOrFail($id);

        return response()->json([
            'name'        => $employee->full_name,
            'system_id'   => $employee->system_id,
            'barcode_id'  => $employee->barcode_id ?: '—',
            'folder_code' => $employee->folder?->folder_code ?: '—',
            'location'    => $employee->folderLocation?->full_location ?: '—',
            'company'     => $employee->company?->name ?: '— Not Assigned —',
            'date_hired'  => $employee->date_hired ? $employee->date_hired->format('F d, Y') : '—',
            'archive_date' => $employee->archive_date ? $employee->archive_date->format('F d, Y') : '—',
            'archived_at' => $employee->deleted_at?->format('F d, Y h:i A'),
            'status'      => ucfirst($employee->status)
        ]);
    }

    /**
     * Get employee update history as JSON (for History modal).
     */
    public function updateHistory(int $id)
    {
        $logs = \App\Models\AuditLog::where('model_type', Employee::class)
            ->where('model_id', $id)
            ->whereIn('action', ['created', 'updated', 'restored'])
            ->with('user')
            ->latest('created_at')
            ->get();

        return response()->json($logs->map(function ($log) {
            return [
                'user_name' => $log->user?->name ?: 'System',
                'user_role' => $log->user?->role ?: 'System',
                'date'      => $log->created_at->format('M d, Y'),
                'time'      => $log->created_at->format('h:i A'),
                'description' => $log->description,
                'changes'   => $log->changes,
                'action'    => $log->action
            ];
        }));
    }
}
